create table if not exists public.professionals (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  category text not null,
  role text not null,
  city text not null,
  description text not null,
  image text not null default 'https://images.unsplash.com/photo-1521791055366-0d553872125f?auto=format&fit=crop&w=900&q=85',
  initials text not null,
  color text not null default '#d9bc71',
  rating numeric(2, 1) not null default 0,
  reviews integer not null default 0,
  price text not null default 'Consulte o profissional',
  experience text not null default 'Novo na mão certa',
  availability text not null default 'Disponível para contato',
  verified boolean not null default true,
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.professionals enable row level security;

create policy "Profissionais publicados são visíveis"
  on public.professionals for select
  using (true);

create policy "Qualquer pessoa pode cadastrar um profissional"
  on public.professionals for insert
  with check (true);